[project]
name = "kts-kyoshi-api"
version = "0.1.0"
description = ""
authors = [{ name = "Andrew Wong", email = "wongwong.wong@gmail.com" }]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "flask>=3.0.3,<4",
    "flask-cors>=4.0.1,<5",
    "openai>=1.26.0,<2",
    "sqlalchemy>=2.0.30,<3",
    "alembic>=1.13.1,<2",
    "psycopg>=3.1.19,<4",
    "importlib>=1.0.4,<2",
    "google-auth[requests]>=2.29.0,<3",
    "fsrs>=2.1.0,<3",
]

[dependency-groups]
dev = [
    "ruff>=0.4.4,<0.5",
]
