"""Types for LLM chat messages and other domain objects."""

from dataclasses import dataclass
import datetime
import json
import logging
import uuid

from pydantic import BaseModel, ValidationError

from data_types.lesson_types import JapaneseLesson


logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)


@dataclass
class Chat:
    user_id: uuid.UUID
    chat_id: uuid.UUID
    chat_name: str
    created_at: datetime.datetime


class ChatMessage(BaseModel):
    """A single message in a chat.

    `content` holds plain text (user/system messages and legacy assistant
    replies). `lesson` holds a structured JapaneseLesson generated by the model.
    """

    role: str
    content: str | None = None
    lesson: JapaneseLesson | None = None

    def to_llm_message(self) -> dict:
        """Shape the message for the OpenAI-compatible chat completions API."""
        if self.lesson is not None:
            return {"role": self.role, "content": self.lesson.model_dump_json()}
        return {"role": self.role, "content": self.content}


def dict_to_chat_message(data: dict) -> ChatMessage:
    # Backwards compatibility: earlier messages stored tool calls instead of a
    # structured lesson. Convert them on read.
    if not data.get("lesson") and data.get("tool_calls"):
        try:
            arguments = json.loads(data["tool_calls"][0]["function"]["arguments"])
            data = {"role": data["role"], "lesson": arguments}
        except (KeyError, IndexError, ValueError):
            logger.warning("Couldn't convert legacy tool_calls message: %s", data)

    try:
        return ChatMessage.model_validate(data)
    except ValidationError:
        logger.warning("Couldn't parse chat message: %s", data)
        return ChatMessage(role=data.get("role", "assistant"))