"""reverse flash cards

Revision ID: 637ab15db69d
Revises: 9615506a6a35
Create Date: 2024-06-14 06:29:17.559905

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "637ab15db69d"
down_revision: Union[str, None] = "9615506a6a35"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "flash_card",
        sa.Column(
            "reverse", sa.Boolean(), server_default=sa.text("FALSE"), nullable=False
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "settings",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::JSONB"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "settings")
    op.drop_column("flash_card", "reverse")
    # ### end Alembic commands ###
