"""add is_active col to flashcard table

Revision ID: eb49c25d4954
Revises: e18b7445c38d
Create Date: 2024-05-18 21:02:27.153567

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "eb49c25d4954"
down_revision: Union[str, None] = "e18b7445c38d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "flash_card",
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("TRUE"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("flash_card", "is_active")
    # ### end Alembic commands ###
