"""create flashcard table

Revision ID: e18b7445c38d
Revises: abe0e55aef7e
Create Date: 2024-05-18 18:18:35.385578

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e18b7445c38d"
down_revision: Union[str, None] = "abe0e55aef7e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "flash_card",
        sa.Column("flash_card_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("chat_id", sa.UUID(), nullable=False),
        sa.Column("chat_message_id", sa.UUID(), nullable=False),
        sa.Column("flash_card_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column("fsrs", sa.JSON(), nullable=False),
        sa.Column(
            "fsrs_due_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("fsrs_state", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("flash_card_id"),
    )
    op.create_index(
        op.f("ix_flash_card_chat_id"), "flash_card", ["chat_id"], unique=False
    )
    op.create_index(
        op.f("ix_flash_card_chat_message_id"),
        "flash_card",
        ["chat_message_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flash_card_user_id"), "flash_card", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_flash_card_user_id"), table_name="flash_card")
    op.drop_index(op.f("ix_flash_card_chat_message_id"), table_name="flash_card")
    op.drop_index(op.f("ix_flash_card_chat_id"), table_name="flash_card")
    op.drop_table("flash_card")
    # ### end Alembic commands ###
