"""add chat_name to Chat

Revision ID: 3c3d4886c3a3
Revises: d5e49be1cae8
Create Date: 2024-05-26 18:24:11.555120

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3c3d4886c3a3"
down_revision: Union[str, None] = "d5e49be1cae8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat",
        sa.Column(
            "chat_name", sa.String(), server_default=sa.text("''"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat", "chat_name")
    # ### end Alembic commands ###
