"""add jlpt_level col to flashcard table

Revision ID: 5e66e73387b5
Revises: eb49c25d4954
Create Date: 2024-05-22 07:43:55.886464

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5e66e73387b5"
down_revision: Union[str, None] = "eb49c25d4954"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "flash_card",
        sa.Column("jlpt_level", sa.Integer(), server_default="-1", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("flash_card", "jlpt_level")
    # ### end Alembic commands ###
